FF_CONFIGURE="--enable-gpl --enable-version3 --disable-debug --disable-doc --enable-small --disable-outdevs --disable-filters --enable-filter='*null*,afade,*fifo,*format,*resample,aeval,allrgb,allyuv,atempo,pan,*bars,color,*key,crop,draw*,eq*,framerate,*_qsv,*_vaapi,*v4l2*,hw*,scale,volume,test*' --enable-schannel --disable-protocols --enable-protocol='file,fd,pipe,http,https,rtp,tcp,udp' --disable-muxers --enable-muxer=rtp --disable-encoders --disable-decoders --enable-decoder='*aac*,h264*,mp3*,mjpeg,rv*' --disable-demuxers --enable-demuxer='h264,mp3,mov,mpjpeg,rtsp,sdp' --disable-zlib --disable-avdevice"
FF_CFLAGS=""
FF_CXXFLAGS=""
FF_LDFLAGS=""
GIT_BRANCH="master"
LICENSE_FILE="COPYING.GPLv3"
